instantcommerce/next-api-decorators

lib/decorators/parameter.decorators.ts
lib/e2e.test.ts
lib/exceptions/BadRequestException.ts
lib/exceptions/index.ts
lib/index.ts
lib/internals/handler.ts
lib/pipes/applyInternalPipes.ts
lib/pipes/index.ts
lib/pipes/parseBoolean.pipe.spec.ts
lib/pipes/parseBoolean.pipe.ts
lib/pipes/parseNumber.pipe.spec.ts
lib/pipes/parseNumber.pipe.ts

* Introduce new exception `BadRequestException`.
* Remove default parsing for `number` and `boolean` types.
* Introduce the ability to add pipes to the `Query` decorator.
* Throw in pipes when the value is invalid.
* Fix tests.

Query pipes

---

.github/workflows/test.yaml
lib/e2e.test.ts
lib/exceptions/BadRequestException.ts
lib/exceptions/HttpException.ts
lib/exceptions/NotFoundException.ts
lib/internals/classValidator.ts
lib/internals/getClassValidatorError.ts
lib/internals/handler.ts
package.json
yarn.lock

Incorporates `class-validator` and `class-transform` in order to use DTOs with the `Body` decorator.
Closes #7

feat: class validator

---

README.md

* Two use cases:
1. Basic
2. Using `class-validator`
* Parameter decorators

docs: usage and parameter decorators

---

README.md

added github release badge and npm badge. feel free to add more if you think of any.

[docs] add badges

---

lib/e2e.test.ts
lib/pipes/parseDate.pipe.spec.ts
lib/pipes/parseDate.pipe.ts

Implemented by taking functions from `validator.js` as commented in the code.
Closes #18

[feat] parse date pipe

---

lib/decorators/httpMethod/httpMethod.decorators.ts
lib/internals/classValidator.spec.ts
lib/internals/handler.ts
lib/internals/loadPackage.spec.ts
lib/pipes/validation.pipe.spec.ts
test/e2e-stream.test.ts
test/e2e.test.ts

[test] more coverage

---

lib/pipes/ParameterPipe.ts
lib/pipes/parsers/parseBoolean.pipe.spec.ts
lib/pipes/parsers/parseBoolean.pipe.ts
lib/pipes/parsers/parseDate.pipe.spec.ts
lib/pipes/parsers/parseDate.pipe.ts
lib/pipes/parsers/parseNumber.pipe.spec.ts
lib/pipes/parsers/parseNumber.pipe.ts
lib/pipes/validateNullable.ts

Added nullable checks in the pipes.

[fix] nullable check

---

README.md

Add `ValidationPipe` to the readme

[docs] validation pipe

---

.github/dependabot.yml

* change the interval to `weekly` to reduce clutter.
* remove `versioning-strategy` as it only updates the lock file most of the time.

[chore] update dependabot config

---

lib/pipes/ParameterPipe.ts
lib/pipes/validators/validateEnum.pipe.ts
lib/pipes/validators/validation.pipe.ts

[docs] JSDoc for pipes

---

.github/workflows/test.yaml
package.json
test/e2e-download.test.ts
test/e2e-params.test.ts
test/e2e-stream.test.ts
test/e2e.test.ts
test/setupServer.ts

Even though it's possible to use Express.js with Next.js, it's good to run the E2E tests against the Next.js' own server as well since that's the default server.

[test] Next.js server

---

package.json

fix: peer dependency versions

---

website/docs/getting-started.md

Fix a broken URL for the examples.

fix(docs): broken examples URL

---

lib/createHandler.ts
lib/internals/getFileDirectory.spec.ts
lib/internals/getFileDirectory.ts
lib/internals/parseRequestUrl.spec.ts
lib/internals/parseRequestUrl.ts

fix: use error stack to determine the directory

---

lib/internals/parseRequestUrl.spec.ts
lib/internals/parseRequestUrl.ts

Fixes the parameterized route for the structure below:
```
- api/route
- index.ts
- [id].ts
```

[fix] parameterized route matching

---

lib/internals/parseRequestUrl.spec.ts
lib/internals/parseRequestUrl.ts

[fix] parse request url

---

lib/internals/getCallerInfo.spec.ts
lib/internals/getCallerInfo.ts

PR for the issue https://github.com/storyofams/next-api-decorators/issues/236

fix: add win32 paths support to getCallerInfo()

---

lib/internals/handler.ts
test/e2e-buffer.test.ts

[fix] send image buffer

---

lib/exceptions/ConflictException.ts
lib/exceptions/ForbiddenException.ts
lib/exceptions/HttpException.spec.ts
lib/exceptions/index.ts
test/e2e-catch.test.ts
website/docs/exceptions.md

Adds `ConflictException` (409) and `ForbiddenException` (403) to library core.
I found myself using these in my own projects pretty quickly, so I figured I'd contribute them directly.
I also updated the docs to now use a different example 🚀 
Thanks again for this awesome library 🌱

[feat] Add ConflictException and ForbiddenException

---

lib/internals/getCallerInfo.spec.ts
lib/internals/getCallerInfo.ts

[fix] last paranthesis

---

lib/internals/validateObject.ts
lib/pipes/validators/validation.pipe.spec.ts

fix: handle empty body validation

---

lib/internals/validateObject.ts
lib/pipes/validators/validation.pipe.spec.ts

[fix] string body validation

---

lib/internals/getCallerInfo.spec.ts
lib/internals/getCallerInfo.ts
lib/internals/parseRequestUrl.ts

fix: error stack parsing

---

lib/internals/getCallerInfo.ts

fix: path separator on windows

---

README.md
website/docs/getting-started.md

I updated my username, so I fixed some links (that get broken when you do this according to GH)!

Update README Links
